#!/usr/bin/env bash
# Compile-check this project. Exit 0 means every package builds and passes vet.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# go vet runs here as well as inside go test: go test vets only the packages it
# tests, so a package with no tests is never vetted there.
#
# Usage: scripts/build.sh [package...]      (defaults to ./...)
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

case "${1:-}" in
  -h|--help) sed -n '2,9p' "${BASH_SOURCE[0]}"; exit 0 ;;
esac

command -v go >/dev/null 2>&1 || { printf 'go not found on PATH\n' >&2; exit 1; }

[ $# -gt 0 ] || set -- ./...
START="$(date +%s)"

go build "$@" || { printf '\nBUILD FAILED\n' >&2; exit 1; }
go vet "$@" || { printf '\nVET FAILED\n' >&2; exit 1; }

printf 'build and vet passed in %ss\n' "$(( $(date +%s) - START ))"
