#!/usr/bin/env bash
# Lint this project with golangci-lint, using .golangci.yml.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# Skips with a message, and exits 0, when golangci-lint is not installed: a lint
# step that fails for a missing tool gets deleted, and takes the checks with it.
#
# Usage: scripts/lint.sh [--fix] [package...]     (defaults to ./...)
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

command -v golangci-lint >/dev/null 2>&1 || {
  printf 'golangci-lint not installed — skipping (https://golangci-lint.run/docs/welcome/install/)\n' >&2
  exit 0
}

FIX=()
case "${1:-}" in
  --fix) FIX=(--fix); shift ;;
  -h|--help) sed -n '2,9p' "${BASH_SOURCE[0]}"; exit 0 ;;
esac
[ $# -gt 0 ] || set -- ./...

golangci-lint run ${FIX[@]+"${FIX[@]}"} "$@"
