#!/usr/bin/env bash
# Run this project's tests.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# Writes a log to $KIT_LOG_ROOT/test-runs/ on every run. That log is not just a
# record: the kit's Stop hook compares its timestamp against your source files to
# tell whether the code you changed has actually been tested. Remove the logging
# and the gate silently starts lying.
#
# Usage: scripts/test.sh [-run PATTERN] [package...]     (defaults to ./...)
#
# KIT_TEST_RACE=0 drops -race where cgo is unavailable. KIT_TEST_TIMEOUT sets the
# go test timeout (default 10m).
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

command -v go >/dev/null 2>&1 || { printf 'go not found on PATH\n' >&2; exit 1; }

RUN=()
while [ $# -gt 0 ]; do
  case "$1" in
    -run)      RUN=(-run "$2"); shift 2 ;;
    -h|--help) sed -n '2,14p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *)         break ;;
  esac
done
[ $# -gt 0 ] || set -- ./...

# -count=1: a cached result is replayed without running anything, so a green run
#   could be last week's.
# -shuffle=on: order-dependent tests fail here rather than on someone else's
#   machine; the seed is printed, so a failure can be replayed with -shuffle=<seed>.
# -race: a data race is a bug the tests only catch when the detector is on.
FLAGS=(-count=1 -shuffle=on -timeout="${KIT_TEST_TIMEOUT:-10m}")
[ "${KIT_TEST_RACE:-1}" = "0" ] || FLAGS+=(-race)

KIT_LOG_ROOT="${KIT_LOG_ROOT:-.agents/state}"
LOG_DIR="$KIT_LOG_ROOT/test-runs"
LOG="$LOG_DIR/go-test.json"
ERR="$LOG_DIR/go-test.stderr"
COUNTS="$LOG_DIR/go-test.counts"
mkdir -p "$LOG_DIR"

START="$(date +%s)"
go test -json "${FLAGS[@]}" ${RUN[@]+"${RUN[@]}"} "$@" >"$LOG" 2>"$ERR"
STATUS=$?

# Counts come from the JSON stream, never the exit code: a -run pattern that
# matches nothing prints "[no tests to run]" and exits 0. Only top-level tests
# are counted — subtests contain a "/" — so a table test counts once.
awk -v counts="$COUNTS" '
  function val(key,   re) {
    re = "\"" key "\":\"[^\"]*\""
    if (match($0, re)) return substr($0, RSTART + length(key) + 4, RLENGTH - length(key) - 5)
    return ""
  }
  function unescape(s) {
    gsub(/\\n/, "\n", s); gsub(/\\t/, "\t", s); gsub(/\\"/, "\"", s)
    return s
  }
  {
    action = val("Action"); pkg = val("Package"); test = val("Test")
    if (action == "output" || action == "build-output") {
      i = index($0, "\"Output\":\"")
      if (i) {
        # The value ends at the first unescaped quote; fields may follow it.
        out = substr($0, i + 10)
        if (match(out, /^([^"\\]|\\.)*/)) out = substr(out, 1, RLENGTH)
        if (action == "build-output") build = build unescape(out)
        else text[pkg SUBSEP test] = text[pkg SUBSEP test] unescape(out)
      }
      next
    }
    if (test != "" && index(test, "/") == 0) {
      if (action == "pass") pass++
      else if (action == "skip") skip++
      else if (action == "fail") { fail++; failed[pkg SUBSEP test] = 1 }
    }
    if (test == "" && action == "fail") failedpkg[pkg] = 1
  }
  END {
    for (k in failed) { split(k, part, SUBSEP); printf "\n--- FAIL: %s  %s\n%s", part[2], part[1], text[k] }
    if (build != "") printf "\n--- build errors\n%s", build
    for (p in failedpkg) if ((p SUBSEP "") in text) printf "\n--- %s\n%s", p, text[p SUBSEP ""]
    printf "%d %d %d\n", pass, fail, skip > counts
  }
' "$LOG"

read -r PASSED FAILED SKIPPED <"$COUNTS" 2>/dev/null || { PASSED=0; FAILED=0; SKIPPED=0; }
ELAPSED="$(( $(date +%s) - START ))s"

if [ "$STATUS" -ne 0 ]; then
  [ -s "$ERR" ] && head -40 "$ERR" >&2
  printf '\nTESTS FAILED (%s): %s passed, %s failed, %s skipped\nLog: %s\n' \
    "$ELAPSED" "$PASSED" "$FAILED" "$SKIPPED" "$LOG" >&2
  exit "$STATUS"
fi

if [ "$PASSED" -eq 0 ]; then
  printf '\nFAILED: exit 0 but no test ran — check the -run pattern, or whether the packages have tests.\nLog: %s\n' "$LOG" >&2
  exit 1
fi

printf '%s passed, %s skipped in %s\nLog: %s\n' "$PASSED" "$SKIPPED" "$ELAPSED" "$LOG"
