#!/usr/bin/env bash
# Manage the local development database defined in compose.yaml.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# Usage: scripts/db.sh <command>
#   up         start Postgres and wait until it is healthy
#   down       stop the containers; data is kept
#   migrate    apply every pending migration
#   rollback   revert the most recent migration
#   status     print the current migration version
#   reset      drop and recreate the database, migrate, then seed — local only
#   seed       load db/seed.sql, if it exists
#   psql       open psql inside the container
#
# Everything runs through `docker compose`, so the only thing that has to be
# installed is a container runtime.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

DB_SERVICE="${DB_SERVICE:-db}"
DB_USER="${POSTGRES_USER:-app}"
DB_NAME="${POSTGRES_DB:-app}"
SEED_FILE="${SEED_FILE:-db/seed.sql}"

die() { printf '%s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker not found — install a container runtime"
docker compose version >/dev/null 2>&1 || die "docker compose not available — is the daemon running?"

psql_in() {
  docker compose exec -T "$DB_SERVICE" psql -v ON_ERROR_STOP=1 -U "$DB_USER" "$@"
}

migrate() {
  docker compose run --rm migrate "$@"
}

# reset destroys data, so it proves the target is local before touching it, in
# the shape of Rails' ProtectedEnvironmentError: default-deny, and one explicit,
# deliberately awkward override rather than a --force a finger can type by habit.
#
#   1. DATABASE_URL, when set, must name localhost, 127.0.0.1, ::1 or the compose
#      service. This script only ever talks to the container, but a DATABASE_URL
#      pointing elsewhere means the shell is configured for another environment,
#      and whatever runs next in it will be too.
#   2. APP_ENV, when set, must be development or test.
#   3. KIT_DB_RESET_CONFIRM=<database name> bypasses both. Typing the name is the
#      confirmation, the way a hosted service makes you type a repo name to delete it.
guard_local() {
  [ "${KIT_DB_RESET_CONFIRM:-}" = "$DB_NAME" ] && return 0

  if [ -n "${DATABASE_URL:-}" ]; then
    local host
    host="$(printf '%s' "$DATABASE_URL" | sed -E 's#^[a-z]+://([^@/]*@)?(\[[^]]*\]|[^:/?]*).*#\2#')"
    case "$host" in
      localhost|127.0.0.1|"[::1]"|::1|"$DB_SERVICE") ;;
      *) die "refusing to reset: DATABASE_URL points at '$host', which is not local.
Set KIT_DB_RESET_CONFIRM=$DB_NAME to override, if you are certain." ;;
    esac
  fi

  case "${APP_ENV:-development}" in
    development|dev|test|local) ;;
    *) die "refusing to reset: APP_ENV is '${APP_ENV}'.
Set KIT_DB_RESET_CONFIRM=$DB_NAME to override, if you are certain." ;;
  esac
}

seed() {
  if [ ! -f "$SEED_FILE" ]; then
    printf 'no %s — nothing to seed\n' "$SEED_FILE"
    return 0
  fi
  psql_in -d "$DB_NAME" <"$SEED_FILE" && printf 'seeded from %s\n' "$SEED_FILE"
}

case "${1:-}" in
  up)
    docker compose up -d --wait "$DB_SERVICE"
    ;;
  down)
    docker compose down
    ;;
  migrate)
    migrate up
    ;;
  rollback)
    migrate down 1
    ;;
  status)
    migrate version
    ;;
  reset)
    guard_local
    printf 'Resetting database %s in the %s container\n' "$DB_NAME" "$DB_SERVICE"
    docker compose up -d --wait "$DB_SERVICE" || exit 1
    psql_in -d postgres \
      -c "DROP DATABASE IF EXISTS \"$DB_NAME\" WITH (FORCE)" \
      -c "CREATE DATABASE \"$DB_NAME\"" || exit 1
    migrate up || exit 1
    seed
    ;;
  seed)
    seed
    ;;
  psql)
    shift
    docker compose exec "$DB_SERVICE" psql -U "$DB_USER" -d "$DB_NAME" "$@"
    ;;
  -h|--help|"")
    sed -n '2,16p' "${BASH_SOURCE[0]}"
    ;;
  *)
    die "unknown command: $1 (see scripts/db.sh --help)"
    ;;
esac
