#!/usr/bin/env bash
# Generate a code map: build targets from ground truth, plus the most-referenced
# type signatures, inside a token budget.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# The output is DERIVED, therefore disposable: it is written under .agents/ and
# gitignored. Never hand-edit it, and never commit it. A hand-maintained map goes
# stale within days and then actively misleads — which is the failure this script
# exists to avoid, not a tradeoff it accepts.
#
# Shape follows aider's repo map (tree-sitter + PageRank + token budget), reduced
# to what runs with no dependencies: reference counting instead of PageRank, and
# a Swift declaration scan instead of tree-sitter.
#
# Usage: scripts/map.sh [--force] [--print]
#   KIT_MAP_TOKENS  approximate token budget (default 1200)
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

FORCE=0
PRINT=0
while [ $# -gt 0 ]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --print) PRINT=1; shift ;;
    --install-hook)
      hook=".git/hooks/post-commit"
      [ -d .git/hooks ] || kit_die "no .git/hooks directory here"
      if [ -e "$hook" ] && ! grep -q 'scripts/map.sh' "$hook" 2>/dev/null; then
        kit_die "$hook already exists and does not call map.sh — merge it by hand"
      fi
      # Backgrounded and silenced: a commit hook must never delay or fail a commit.
      cat >"$hook" <<'HOOK'
#!/usr/bin/env bash
# Refresh the agent code map after each commit. Never blocks or fails the commit.
[ -x scripts/map.sh ] && (scripts/map.sh >/dev/null 2>&1 &)
exit 0
HOOK
      chmod +x "$hook"
      printf 'Installed %s\n' "$hook"
      exit 0 ;;
    -h|--help) sed -n '2,16p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) kit_die "unknown argument: $1" ;;
  esac
done

OUT="$KIT_LOG_ROOT/map.xml"
STAMP="$KIT_LOG_ROOT/.map-stamp"
BUDGET="${KIT_MAP_TOKENS:-1200}"
mkdir -p "$KIT_LOG_ROOT"

# Cache on name+mtime+size of every tracked Swift file, the same signal aider
# uses. Cheap (~0.1s) and a spurious touch only costs one needless regeneration.
current_stamp() {
  git ls-files '*.swift' 2>/dev/null | xargs stat -f '%N %m %z' 2>/dev/null | shasum | cut -d' ' -f1
}

CURRENT="$(current_stamp)"
if [ "$FORCE" -eq 0 ] && [ -f "$OUT" ] && [ "$(cat "$STAMP" 2>/dev/null)" = "$CURRENT" ]; then
  [ "$PRINT" -eq 1 ] && cat "$OUT"
  exit 0
fi

# --- targets: ground truth, never inferred from folder layout -----------------
#
# Xcode groups are virtual and buildable folders still are not target membership,
# so a directory tree cannot tell you what compiles into what. Ask the project.
targets_block() {
  local pa
  pa="$(kit_project_args 2>/dev/null | tr '\n' ' ')"
  if [ -n "$pa" ]; then
    # shellcheck disable=SC2086
    if xcodebuild $pa -list -json 2>/dev/null | python3 -c '
import json,sys
try: d=json.load(sys.stdin)
except Exception: sys.exit(1)
k="workspace" if "workspace" in d else "project"
info=d.get(k,{})
print("  container: %s" % info.get("name","?"))
for label in ("targets","schemes"):
    vals=info.get(label) or []
    if vals: print("  %s: %s" % (label, ", ".join(vals)))
' 2>/dev/null; then
      return 0
    fi
  fi
  return 1
}

# A workspace's -list JSON carries schemes but no targets, and target membership
# is exactly what cannot be inferred from folder layout. Take it from the
# manifest when there is one.
manifest_targets() {
  if [ -f Project.swift ]; then
    printf '  tuist targets: %s\n' \
      "$(grep -A2 '^[[:space:]]*\.target($' Project.swift 2>/dev/null \
         | grep -oE 'name: "[^"]+"' | sed 's/name: "//; s/"//' | tr '\n' ' ')"
    return 0
  fi
  if [ -f project.yml ]; then
    printf '  xcodegen targets: %s\n' \
      "$(awk '/^targets:/{t=1;next} t && /^  [A-Za-z]/{gsub(/:.*/,""); gsub(/ /,""); printf "%s ", $0} t && /^[a-z]/{exit}' project.yml)"
    return 0
  fi
  return 1
}

# --- symbols ------------------------------------------------------------------
symbols_block() {
  command -v python3 >/dev/null 2>&1 || {
    printf '  (python3 unavailable — symbol index skipped)\n'
    return 0
  }
  git ls-files '*.swift' 2>/dev/null | python3 -c '
import re, sys, os, collections

BUDGET_CHARS = int(os.environ.get("KIT_MAP_TOKENS", "1200")) * 4
SKIP = ("generated.swift", ".pb.swift", ".grpc.swift",
        "+coredataproperties.swift", "+coredataclass.swift")
# `class func` is a static method, not a type. Without this guard every such line
# parses as a class literally named "func", and "func" then scores as the most
# referenced symbol in the repository.
NON_NAMES = {"func", "var", "let", "init", "subscript", "deinit", "case"}

files = [f.strip() for f in sys.stdin if f.strip()]
files = [f for f in files if not any(s in f.lower() for s in SKIP)]

TYPE_RE = re.compile(
    r"^\s*(?:@\w+(?:\([^)]*\))?\s+)*"
    r"(?P<acl>public|internal|private|fileprivate|open)?\s*"
    r"(?:final\s+)?(?P<kind>class|struct|enum|protocol|actor)\s+(?P<name>\w+)")
FUNC_RE = re.compile(
    r"^\s*(?:@\w+(?:\([^)]*\))?\s+)*(?P<acl>public|internal|open)?\s*"
    r"(?:(?:static|final|class|override|mutating)\s+)*func\s+(?P<name>\w+)")
IDENT_RE = re.compile(r"[A-Za-z_]\w*")

decls, tokens = {}, {}
for p in files:
    try:
        text = open(p, encoding="utf-8", errors="ignore").read()
    except OSError:
        continue
    tokens[p] = collections.Counter(IDENT_RE.findall(text))
    found = []
    for line in text.splitlines():
        m = TYPE_RE.match(line)
        if m and m.group("name") not in NON_NAMES:
            found.append(("type", m.group("name"),
                          line.strip().rstrip("{").strip(),
                          m.group("acl") == "public"))
            continue
        m = FUNC_RE.match(line)
        if m:
            found.append(("func", m.group("name"),
                          line.strip().rstrip("{").strip(),
                          m.group("acl") == "public"))
    if found:
        decls[p] = found

# Where is each type name declared? A name declared in several files — `Section`,
# `Item`, `State` — cannot be counted, because occurrences elsewhere refer to
# whichever one is in scope. Counting them anyway is how a generic nested enum
# outranks the domain types that actually matter.
homes = collections.defaultdict(list)
for p, ds in decls.items():
    for kind, name, _, _ in ds:
        if kind == "type" and len(name) > 2:
            homes[name].append(p)

refs = {}
for name, hs in homes.items():
    if len(hs) != 1:
        refs[name] = None
        continue
    h = hs[0]
    refs[name] = sum(c[name] for p, c in tokens.items() if p != h)

def score(p):
    total = 0
    for kind, name, _, pub in decls[p]:
        if kind != "type":
            continue
        r = refs.get(name)
        if r:
            total += r
        if pub:
            total += 5
    return total

ranked = sorted(decls, key=lambda p: (-score(p), p))

def fmt(name):
    r = refs.get(name)
    return "[refs %d]" % r if r else ""

out, used, shown = [], 0, 0
for p in ranked:
    types = [d for d in decls[p] if d[0] == "type"]
    if not types or score(p) == 0:
        continue
    funcs = [d for d in decls[p] if d[0] == "func"][:3]
    chunk = ["  %s" % p]
    for _, name, sig, _ in types[:3]:
        chunk.append("    %s   %s" % (sig, fmt(name)))
    for _, _, sig, _ in funcs:
        chunk.append("      %s" % sig)
    block = "\n".join(chunk)
    if used + len(block) > BUDGET_CHARS:
        break
    out.append(block)
    used += len(block)
    shown += 1

remaining = len([p for p in ranked if score(p) > 0]) - shown
if remaining > 0:
    out.append("  … %d further files carry declarations; grep for them" % remaining)

print("\n".join(out) if out else "  (no Swift declarations found)")
'
}

{
  printf '<codemap>\n'
  printf '<generated-by>scripts/map.sh — derived and disposable; never hand-edit or commit</generated-by>\n'
  printf '<budget-tokens>%s</budget-tokens>\n' "$BUDGET"
  printf '<targets>\n'
  found=0
  targets_block && found=1
  manifest_targets && found=1
  [ "$found" -eq 0 ] && printf '  (no Xcode project, workspace, or manifest found)\n'
  printf '</targets>\n'
  printf '<symbols note="ranked by how often each type is referenced elsewhere; signatures only">\n'
  KIT_MAP_TOKENS="$BUDGET" symbols_block
  printf '</symbols>\n'
  printf '</codemap>\n'
} >"$OUT"

printf '%s\n' "$CURRENT" >"$STAMP"

if [ "$PRINT" -eq 1 ]; then
  cat "$OUT"
else
  printf 'Wrote %s (%s lines, budget ~%s tokens)\n' "$OUT" "$(wc -l <"$OUT" | tr -d ' ')" "$BUDGET"
fi
