#!/usr/bin/env bash
# Point this checkout's agent tooling at Xcode's build cache.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# Two consumers need the same machine-specific fact — the DerivedData folder,
# whose name is a hash of the checkout path and so cannot be committed:
#
#   .xcodebuildmcp/config.yaml   derivedDataPath for the xcodebuildmcp CLI and MCP server
#   buildServer.json + .compile  compile flags for sourcekit-lsp
#
# Why it matters. Left unset, xcodebuildmcp builds into its own isolated store
# under ~/Library/Developer/XcodeBuildMCP/workspaces/ — a cold build and a second
# multi-GB cache that nothing else ever reads. Pointed at Xcode's folder,
# xcodebuildmcp, Xcode, scripts/build.sh and scripts/test.sh all share one warm
# cache. Without buildServer.json, sourcekit-lsp falls back to a macOS target and
# reports "No such module 'UIKit'" on every file in an iOS framework.
#
# Run once per checkout, and again after moving the repo, changing
# Xcode > Settings > Locations > Derived Data, or adding source files.
#
# Usage: scripts/setup-tooling.sh [--scheme NAME] [--print] [--no-lsp] [--no-mcp]
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

SCHEME=""
PRINT_ONLY=0
SETUP_LSP=1
SETUP_MCP=1

while [ $# -gt 0 ]; do
  case "$1" in
    --scheme)  SCHEME="$2"; shift 2 ;;
    --print)   PRINT_ONLY=1; shift ;;
    --no-lsp)  SETUP_LSP=0; shift ;;
    --no-mcp)  SETUP_MCP=0; shift ;;
    -h|--help) sed -n '2,22p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)         kit_die "unknown argument: $1" ;;
  esac
done

PROJECT_ARGS=()
while IFS= read -r line; do
  [ -n "$line" ] && PROJECT_ARGS+=("$line")
done < <(kit_project_args)
[ "${#PROJECT_ARGS[@]}" -gt 0 ] || kit_die "no .xcworkspace or .xcodeproj found in $(pwd)"

[ -n "$SCHEME" ] || SCHEME="$(kit_scheme "${PROJECT_ARGS[@]}")"
[ -n "$SCHEME" ] || kit_die "could not determine a scheme; pass --scheme NAME"

DERIVED_DATA="$(kit_derived_data "${PROJECT_ARGS[@]}" -scheme "$SCHEME")"
[ -n "$DERIVED_DATA" ] || kit_die "could not resolve this checkout's DerivedData folder"

if [ "$PRINT_ONLY" -eq 1 ]; then
  printf '%s\n' "$DERIVED_DATA"
  exit 0
fi

# --- xcodebuildmcp ----------------------------------------------------------

TEMPLATE=".xcodebuildmcp/config.template.yaml"
CONFIG=".xcodebuildmcp/config.yaml"

if [ "$SETUP_MCP" -eq 1 ] && [ -f "$TEMPLATE" ]; then
  # projectPath and workspacePath are mutually exclusive in the config schema, so
  # the key is chosen from what the project actually is rather than written twice.
  PROJECT_KEY="projectPath"
  [ "${PROJECT_ARGS[0]}" = "-workspace" ] && PROJECT_KEY="workspacePath"
  PROJECT_PATH="${PROJECT_ARGS[1]#./}"

  # A NAME, never the UDID: UDIDs are regenerated per machine and per Xcode
  # install, so a committed one resolves to nothing on the next checkout.
  # xcodebuildmcp re-resolves the name to this machine's UDID at runtime.
  SIM_UDID="$(kit_sim_udid iOS)"
  SIM_NAME="$(kit_sim_name "$SIM_UDID" iOS)"

  mkdir -p "$(dirname "$CONFIG")"
  # Substituted in awk rather than sed: a DerivedData path can contain characters
  # sed reads as delimiters or backreferences.
  awk -v dd="$DERIVED_DATA" -v pkey="$PROJECT_KEY" -v ppath="$PROJECT_PATH" \
      -v scheme="$SCHEME" -v simname="$SIM_NAME" '
    function subst(line, token, value,   i) {
      while ((i = index(line, token)) > 0) {
        line = substr(line, 1, i - 1) value substr(line, i + length(token))
      }
      return line
    }
    # simulatorName is schema-typed as a non-empty string, so on a machine with no
    # iOS simulator the line has to GO, not be written blank — a blank one makes
    # the whole config invalid and takes derivedDataPath down with it.
    simname == "" && index($0, "@SIMULATOR_NAME@") > 0 { next }
    {
      $0 = subst($0, "@DERIVED_DATA_PATH@", dd)
      $0 = subst($0, "@PROJECT_KEY@",       pkey)
      $0 = subst($0, "@PROJECT_PATH@",      ppath)
      $0 = subst($0, "@SCHEME@",            scheme)
      $0 = subst($0, "@SIMULATOR_NAME@",    simname)
      print
    }
  ' "$TEMPLATE" >"$CONFIG"

  printf 'Wrote %s\n' "$CONFIG"
  printf '  %-16s %s\n' "$PROJECT_KEY" "$PROJECT_PATH"
  printf '  %-16s %s\n' "scheme" "$SCHEME"
  printf '  %-16s %s\n' "simulatorName" "${SIM_NAME:-<none available>}"
  printf '  %-16s %s\n' "derivedDataPath" "$DERIVED_DATA"
elif [ "$SETUP_MCP" -eq 1 ]; then
  kit_warn "no $TEMPLATE — skipping xcodebuildmcp config"
fi

# --- sourcekit-lsp ----------------------------------------------------------

# `config` binds the scheme; `parse` is what actually supplies the compile flags,
# and both are needed. Command-line xcodebuild never writes the .xcactivitylog
# that xcode-build-server watches — only the Xcode IDE does — so a bare `config`
# leaves the server flagless and sourcekit-lsp silently falls back to a macOS
# target. Feed it the raw logs build.sh and test.sh already tee aside.
[ "$SETUP_LSP" -eq 1 ] || exit 0

if ! command -v xcode-build-server >/dev/null 2>&1; then
  kit_warn "xcode-build-server not installed — skipping sourcekit-lsp setup"
  kit_warn "  brew install xcode-build-server, then re-run"
  exit 0
fi

xcode-build-server config "${PROJECT_ARGS[@]}" -scheme "$SCHEME" >/dev/null 2>&1

# Order is load-bearing. `.compile` holds one flag set per file and the last source
# to mention a file wins, so the bound scheme's own log goes LAST: shared sources
# must end up with flags for the platform buildServer.json names, or a stray tvOS
# log silently gives every shared file appletvsimulator flags and each iOS-side
# lookup through them fails to resolve.
SCHEME_LOG="$KIT_LOG_ROOT/build-logs/${SCHEME// /_}.log"
RAW_LOGS=()
for log in "$KIT_LOG_ROOT"/test-runs/*.log "$KIT_LOG_ROOT"/build-logs/*.log; do
  [ -f "$log" ] || continue
  [ "$log" = "$SCHEME_LOG" ] && continue
  RAW_LOGS+=("$log")
done
[ -f "$SCHEME_LOG" ] && RAW_LOGS+=("$SCHEME_LOG")

# Rebuilt from scratch so a re-run drops flags for files that no longer exist.
rm -f .compile

# `config` alone leaves kind "xcode", and in that mode the server hunts for the
# .xcactivitylog files that only the Xcode IDE writes — a command-line xcodebuild
# never produces one, so every lookup silently returns nothing. A parse WITHOUT -o
# is what rewrites the file to kind "manual"; -o only writes the compile DB.
#
# `parse -s` is tried first because it is the only path that also records
# indexStorePath. It exits 0 even when it finds nothing ("no newest_logpath
# xcactivitylog"), so the fallback must test the OUTCOME, never the exit status.
xcode-build-server parse -s "$DERIVED_DATA" >/dev/null 2>&1
if ! grep -q '"kind" *: *"manual"' buildServer.json 2>/dev/null; then
  [ "${#RAW_LOGS[@]}" -gt 0 ] && xcode-build-server parse "${RAW_LOGS[0]}" >/dev/null 2>&1
fi

# Union, not either/or: `-a` overwrites same-file entries, so overlap is harmless
# and re-runs are idempotent. A cached build emits almost no compile commands, so
# no single log covers the tree on its own.
for log in ${RAW_LOGS+"${RAW_LOGS[@]}"}; do
  xcode-build-server parse -a -o .compile "$log" >/dev/null 2>&1
done

if grep -q '"kind" *: *"manual"' buildServer.json 2>/dev/null; then
  printf 'Wrote buildServer.json  (scheme -> %s)\n' "$SCHEME"
else
  kit_warn "buildServer.json is still kind \"xcode\" — sourcekit-lsp will resolve nothing."
  kit_warn "  Run scripts/build.sh to produce a log to parse, then re-run this script."
fi

if ! grep -q '"indexStorePath"' buildServer.json 2>/dev/null; then
  kit_warn "no index store bound: this checkout has no Xcode IDE build log yet."
  kit_warn "  Compile flags still work. Build once in Xcode and re-run to add the index."
fi

if [ ! -s .compile ]; then
  kit_warn "no compile flags found — run scripts/build.sh, then re-run this script"
  exit 0
fi

# Every entry carries "directory", swift-module and clang entries alike, so this
# counts the array without needing a JSON parser.
printf 'Wrote .compile  (%s compile entries — sourcekit-lsp ready)\n' \
  "$(grep -c '"directory"' .compile 2>/dev/null || echo 0)"
