#!/usr/bin/env bash
# Compile-check this project. Exit 0 means it compiles.
#
# Generated by /kit:scripts. Safe to edit — it is yours now.
#
# Never cleans. Correctness comes from the build system reading sources on disk
# every run; a clean only throws away the cache that makes this fast.
#
# Usage: scripts/build.sh [--scheme NAME] [--device] [--isolated]
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

SCHEME=""
USE_DEVICE=0
TIMEOUT="${KIT_BUILD_TIMEOUT:-1800}"

while [ $# -gt 0 ]; do
  case "$1" in
    --scheme)   SCHEME="$2"; shift 2 ;;
    --device)   USE_DEVICE=1; shift ;;
    --isolated) KIT_DERIVED_DATA="${KIT_DERIVED_DATA:-.build/derived-data}"; export KIT_DERIVED_DATA; shift ;;
    -h|--help)  sed -n '2,9p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *)          kit_die "unknown argument: $1" ;;
  esac
done

START="$(kit_now)"
kit_apply_xcode_defaults

PROJECT_ARGS=()
while IFS= read -r line; do
  [ -n "$line" ] && PROJECT_ARGS+=("$line")
done < <(kit_project_args) || kit_die "no .xcworkspace or .xcodeproj found in $(pwd)"
[ "${#PROJECT_ARGS[@]}" -gt 0 ] || kit_die "no .xcworkspace or .xcodeproj found in $(pwd)"

[ -n "$SCHEME" ] || SCHEME="$(kit_scheme "${PROJECT_ARGS[@]}")"
[ -n "$SCHEME" ] || kit_die "could not determine a scheme; pass --scheme NAME"

if [ "$USE_DEVICE" -eq 1 ]; then
  DESTINATION='generic/platform=iOS'
else
  UDID="$(kit_sim_udid iOS)"
  if [ -n "$UDID" ]; then
    DESTINATION="platform=iOS Simulator,id=$UDID"
    kit_boot_async "$UDID"
  else
    # Warned because the cost is invisible: a generic destination resolves several
    # architectures and evicts the shared DerivedData slice every other entry
    # point relies on.
    kit_warn "no available simulator — falling back to a generic destination (slower, evicts cache)"
    DESTINATION='generic/platform=iOS Simulator'
  fi
fi

FLAGS=()
while IFS= read -r line; do
  [ -n "$line" ] && FLAGS+=("$line")
done < <(kit_common_flags)

kit_resolve_packages_if_stale "${PROJECT_ARGS[@]}"

LOG="$KIT_LOG_ROOT/build-logs/${SCHEME// /_}.log"
printf 'Building %s for %s\n' "$SCHEME" "$DESTINATION"

kit_run_logged "$LOG" \
  timeout "$TIMEOUT" xcodebuild \
    "${PROJECT_ARGS[@]}" \
    -scheme "$SCHEME" \
    -destination "$DESTINATION" \
    "${FLAGS[@]}" \
    build
STATUS=$?

ELAPSED="$(kit_elapsed "$(( $(kit_now) - START ))")"

if [ "$STATUS" -ne 0 ]; then
  printf '\nBUILD FAILED (%s) — see %s\n' "$ELAPSED" "$LOG" >&2
  grep -E '(error|fatal error):' "$LOG" | sort -u | head -20 >&2
  exit "$STATUS"
fi

printf '\nBuild succeeded in %s\n' "$ELAPSED"
printf 'Compiled %s file(s). Log: %s\n' \
  "$(grep -c '^SwiftCompile ' "$LOG" 2>/dev/null || echo 0)" "$LOG"
