#!/usr/bin/env bash
# Lint this project.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# Exits non-zero on error severity ONLY. Warnings are reported and do not fail:
# a lint step that fails on warnings in an existing codebase gets disabled within
# a week, taking the error checks with it.
#
# Usage: scripts/lint.sh [--fix] [path...]
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

command -v swiftlint >/dev/null 2>&1 || {
  printf 'swiftlint not installed — skipping (brew install swiftlint)\n' >&2
  exit 0
}

FIX=0
if [ "${1:-}" = "--fix" ]; then
  FIX=1
  shift
fi

if [ "$FIX" -eq 1 ]; then
  swiftlint --fix --force-exclude --quiet "$@"
fi

OUT="$(swiftlint lint --force-exclude --quiet "$@" 2>/dev/null)"
ERRORS="$(printf '%s\n' "$OUT" | grep -c ': error:' || true)"
WARNINGS="$(printf '%s\n' "$OUT" | grep -c ': warning:' || true)"

[ -n "$OUT" ] && printf '%s\n' "$OUT"

printf '\n%s error(s), %s warning(s)\n' "$ERRORS" "$WARNINGS"

[ "$ERRORS" -gt 0 ] && exit 1
exit 0
