#!/usr/bin/env bash
# Run this project's tests.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# Writes a log to $KIT_LOG_ROOT/test-runs/ on every run. That log is not just a
# record: the kit's Stop hook compares its timestamp against your source files to
# tell whether the code you changed has actually been tested. Remove the logging
# and the gate silently starts lying.
#
# Usage: scripts/test.sh [--scheme NAME] [--only-testing ID]... [--isolated]
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

SCHEME=""
ONLY=()
TIMEOUT="${KIT_TEST_TIMEOUT:-900}"

while [ $# -gt 0 ]; do
  case "$1" in
    --scheme)       SCHEME="$2"; shift 2 ;;
    --only-testing) ONLY+=("-only-testing" "$2"); shift 2 ;;
    --isolated)     KIT_DERIVED_DATA="${KIT_DERIVED_DATA:-.build/derived-data}"; export KIT_DERIVED_DATA; shift ;;
    -h|--help)      sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *)              kit_die "unknown argument: $1" ;;
  esac
done

START="$(kit_now)"
kit_apply_xcode_defaults

PROJECT_ARGS=()
while IFS= read -r line; do
  [ -n "$line" ] && PROJECT_ARGS+=("$line")
done < <(kit_project_args)
[ "${#PROJECT_ARGS[@]}" -gt 0 ] || kit_die "no .xcworkspace or .xcodeproj found in $(pwd)"

[ -n "$SCHEME" ] || SCHEME="$(kit_scheme "${PROJECT_ARGS[@]}")"
[ -n "$SCHEME" ] || kit_die "could not determine a scheme; pass --scheme NAME"

UDID="$(kit_sim_udid iOS)"
[ -n "$UDID" ] || kit_die "no available iOS simulator to run tests on"
kit_boot_async "$UDID"
DESTINATION="platform=iOS Simulator,id=$UDID"

FLAGS=()
while IFS= read -r line; do
  [ -n "$line" ] && FLAGS+=("$line")
done < <(kit_common_flags)

SAFE="${SCHEME// /_}"
LOG_DIR="$KIT_LOG_ROOT/test-runs"
LOG="$LOG_DIR/$SAFE.log"
RESULT="$LOG_DIR/$SAFE.xcresult"
mkdir -p "$LOG_DIR"
rm -rf "$RESULT" 2>/dev/null

kit_resolve_packages_if_stale "${PROJECT_ARGS[@]}"

# Two-phase: compiling once and then replaying a prebuilt .xctestrun skips the
# project reload and target-graph replan on every subsequent run. Measured at 3s
# versus 14s per invocation on a large project. Falls back to a single-phase run
# when the .xctestrun cannot be located.
printf 'Building tests for %s\n' "$SCHEME"
kit_run_logged "$LOG_DIR/$SAFE.build.log" \
  timeout "$TIMEOUT" xcodebuild \
    "${PROJECT_ARGS[@]}" -scheme "$SCHEME" -destination "$DESTINATION" \
    "${FLAGS[@]}" build-for-testing
BUILD_STATUS=$?

if [ "$BUILD_STATUS" -ne 0 ]; then
  printf '\nTEST BUILD FAILED — see %s\n' "$LOG_DIR/$SAFE.build.log" >&2
  grep -E '(error|fatal error):' "$LOG_DIR/$SAFE.build.log" | sort -u | head -20 >&2
  exit "$BUILD_STATUS"
fi

BUILD_DIR="$(xcodebuild "${PROJECT_ARGS[@]}" -scheme "$SCHEME" -destination "$DESTINATION" \
  -showBuildSettings 2>/dev/null | awk -F' = ' '/ BUILD_DIR = /{print $2; exit}')"
# The products directory is SHARED across schemes, so it accumulates one .xctestrun per scheme
# ever built. Matching anything other than this scheme's own file silently runs a different
# target's tests and reports them as this scheme's — a green run that tested the wrong code.
# If this scheme's file is not there, fall back to the slower single-phase run rather than
# guessing.
XCTESTRUN=""
if [ -n "$BUILD_DIR" ] && [ -d "$BUILD_DIR" ]; then
  XCTESTRUN="$(find "$BUILD_DIR" -maxdepth 1 -name "${SCHEME}_*.xctestrun" -print 2>/dev/null \
    | head -1)"
fi

printf 'Testing %s on %s\n' "$SCHEME" "$UDID"
if [ -n "$XCTESTRUN" ]; then
  kit_run_logged "$LOG" \
    timeout "$TIMEOUT" xcodebuild \
      -xctestrun "$XCTESTRUN" -destination "$DESTINATION" \
      -resultBundlePath "$RESULT" \
      ${ONLY[@]+"${ONLY[@]}"} \
      test-without-building
else
  kit_warn "no .xctestrun located — falling back to a single-phase run (slower)"
  kit_run_logged "$LOG" \
    timeout "$TIMEOUT" xcodebuild \
      "${PROJECT_ARGS[@]}" -scheme "$SCHEME" -destination "$DESTINATION" \
      "${FLAGS[@]}" -resultBundlePath "$RESULT" \
      ${ONLY[@]+"${ONLY[@]}"} \
      test
fi
STATUS=$?

# Counts come from the RAW log, never the formatter: xcpretty silently drops all
# Swift Testing output. XCTest and Swift Testing report differently, so read both.
count_of() { grep -oE "$1" "$LOG" 2>/dev/null | grep -oE '[0-9]+' | sort -rn | head -1; }
XCTEST_N="$(count_of 'Executed [0-9]+ test')"
SWITEST_N="$(count_of 'Test run with [0-9]+ test')"
TOTAL=$(( ${XCTEST_N:-0} + ${SWITEST_N:-0} ))

ELAPSED="$(kit_elapsed "$(( $(kit_now) - START ))")"

if [ "$STATUS" -ne 0 ]; then
  # Both the log and the result bundle are overwritten on the next run, so an
  # intermittent failure is otherwise unattributable. Preserve it now.
  KEEP="$LOG_DIR/failures/$SAFE-$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$KEEP"
  cp "$LOG" "$KEEP/" 2>/dev/null
  cp -R "$RESULT" "$KEEP/" 2>/dev/null
  printf '\nTESTS FAILED (%s, %s tests) — preserved in %s\n' "$ELAPSED" "$TOTAL" "$KEEP" >&2
  if command -v xcrun >/dev/null 2>&1 && [ -d "$RESULT" ]; then
    xcrun xcresulttool get test-results summary --path "$RESULT" --format json 2>/dev/null \
      | grep -oE '"(title|failureText)"[^,]*' | head -20 >&2
  fi
  exit "$STATUS"
fi

# xcodebuild exits 0 when a filter matches nothing. A green run that executed no
# tests is a false pass, and the most expensive kind.
if [ "$TOTAL" -eq 0 ]; then
  printf '\nFAILED: exit 0 but 0 tests ran — check the scheme or --only-testing filter.\n' >&2
  printf 'Log: %s\n' "$LOG" >&2
  exit 1
fi

printf '\n%s tests passed in %s\n' "$TOTAL" "$ELAPSED"
printf 'Log: %s\n' "$LOG"
