#!/usr/bin/env bash
# Run this project's tests.
#
# Generated by /vvkit:scripts. Safe to edit — it is yours now.
#
# Writes a log to $KIT_LOG_ROOT/test-runs/ on every run. That log is not just a
# record: the kit's Stop hook compares its timestamp against your source files to
# tell whether the code you changed has actually been tested. Remove the logging
# and the gate silently starts lying.
#
# Usage: scripts/test.sh [--scheme NAME] [--only-testing ID]... [--isolated]
#
# KIT_TEST_SCHEME overrides the scheme for tests only, leaving build.sh alone.
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
. "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

SCHEME=""
ONLY=()
TIMEOUT="${KIT_TEST_TIMEOUT:-900}"

while [ $# -gt 0 ]; do
  case "$1" in
    --scheme)       SCHEME="$2"; shift 2 ;;
    --only-testing) ONLY+=("-only-testing" "$2"); shift 2 ;;
    --isolated)     KIT_DERIVED_DATA="${KIT_DERIVED_DATA:-.build/derived-data}"; export KIT_DERIVED_DATA; shift ;;
    -h|--help)      sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *)              kit_die "unknown argument: $1" ;;
  esac
done

START="$(kit_now)"
kit_apply_xcode_defaults

PROJECT_ARGS=()
while IFS= read -r line; do
  [ -n "$line" ] && PROJECT_ARGS+=("$line")
done < <(kit_project_args)
[ "${#PROJECT_ARGS[@]}" -gt 0 ] || kit_die "no .xcworkspace or .xcodeproj found in $(pwd)"

# The scheme that builds the app is frequently not the scheme that runs the tests.
# Where the suites belong to frameworks rather than the app, the app's own scheme
# has no testables and a run reports "no test bundles available" and 0 tests —
# which looks like a broken script rather than a scheme that was never meant to
# test anything. KIT_TEST_SCHEME names the aggregate without changing what
# build.sh compiles, since building the aggregate pulls in every extension.
[ -n "$SCHEME" ] || SCHEME="${KIT_TEST_SCHEME:-}"
[ -n "$SCHEME" ] || SCHEME="$(kit_scheme "${PROJECT_ARGS[@]}")"
[ -n "$SCHEME" ] || kit_die "could not determine a scheme; pass --scheme NAME"

UDID="$(kit_sim_udid iOS)"
[ -n "$UDID" ] || kit_die "no available iOS simulator to run tests on"
kit_boot_async "$UDID"
DESTINATION="platform=iOS Simulator,id=$UDID"

FLAGS=()
while IFS= read -r line; do
  [ -n "$line" ] && FLAGS+=("$line")
done < <(kit_common_flags)

SAFE="${SCHEME// /_}"
LOG_DIR="$KIT_LOG_ROOT/test-runs"
LOG="$LOG_DIR/$SAFE.log"
RESULT="$LOG_DIR/$SAFE.xcresult"
mkdir -p "$LOG_DIR"
rm -rf "$RESULT" 2>/dev/null

kit_resolve_packages_if_stale "${PROJECT_ARGS[@]}"

# Two-phase: compiling once and then replaying a prebuilt .xctestrun skips the
# project reload and target-graph replan on every subsequent run. Measured at 3s
# versus 14s per invocation on a large project. Falls back to a single-phase run
# when the .xctestrun cannot be located.
printf 'Building tests for %s\n' "$SCHEME"
kit_run_logged "$LOG_DIR/$SAFE.build.log" \
  timeout "$TIMEOUT" xcodebuild \
    "${PROJECT_ARGS[@]}" -scheme "$SCHEME" -destination "$DESTINATION" \
    "${FLAGS[@]}" build-for-testing
BUILD_STATUS=$?

if [ "$BUILD_STATUS" -ne 0 ]; then
  printf '\nTEST BUILD FAILED — see %s\n' "$LOG_DIR/$SAFE.build.log" >&2
  grep -E '(error|fatal error):' "$LOG_DIR/$SAFE.build.log" | sort -u | head -20 >&2
  exit "$BUILD_STATUS"
fi

BUILD_DIR="$(xcodebuild "${PROJECT_ARGS[@]}" -scheme "$SCHEME" -destination "$DESTINATION" \
  -showBuildSettings 2>/dev/null | awk -F' = ' '/ BUILD_DIR = /{print $2; exit}')"
# The products directory is SHARED across schemes, so it accumulates one .xctestrun per scheme
# ever built. Matching anything other than this scheme's own file silently runs a different
# target's tests and reports them as this scheme's — a green run that tested the wrong code.
# If this scheme's file is not there, fall back to the slower single-phase run rather than
# guessing.
# NEWEST WINS. The products directory is never cleaned, so a scheme accumulates an .xctestrun per
# destination it has ever been built for, and an older one survives a change that should have
# invalidated it. `find | head -1` returns directory order, not time order — observed replaying a
# stale bundle-less file written before a scheme gained its test targets, so the run reported
# "no test bundles available" and 0 tests while a correct file sat beside it.
XCTESTRUN=""
if [ -n "$BUILD_DIR" ] && [ -d "$BUILD_DIR" ]; then
  XCTESTRUN="$(find "$BUILD_DIR" -maxdepth 1 -name "${SCHEME}_*.xctestrun" \
    -exec stat -f '%m %N' {} + 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-)"
fi

printf 'Testing %s on %s\n' "$SCHEME" "$UDID"
if [ -n "$XCTESTRUN" ]; then
  # -xctestrun names no project, so xcodebuild has nothing to hash a DerivedData
  # folder from and mints a fresh anonymous one per invocation to hold its Logs/
  # and TestResults/. Left alone that is one orphan directory per test run —
  # observed as 86 of them, 24-28K each, beside the single real 1GB cache.
  # Point it at the store the products came from; the .xctestrun lives inside it.
  # This does not contradict the "omit -derivedDataPath" rule in lib/common.sh:
  # that rule protects the *build* cache from being split, and nothing compiles
  # in this phase.
  kit_run_logged "$LOG" \
    timeout "$TIMEOUT" xcodebuild \
      -xctestrun "$XCTESTRUN" -destination "$DESTINATION" \
      -derivedDataPath "${XCTESTRUN%%/Build/Products/*}" \
      -resultBundlePath "$RESULT" \
      ${ONLY[@]+"${ONLY[@]}"} \
      test-without-building
else
  kit_warn "no .xctestrun located — falling back to a single-phase run (slower)"
  kit_run_logged "$LOG" \
    timeout "$TIMEOUT" xcodebuild \
      "${PROJECT_ARGS[@]}" -scheme "$SCHEME" -destination "$DESTINATION" \
      "${FLAGS[@]}" -resultBundlePath "$RESULT" \
      ${ONLY[@]+"${ONLY[@]}"} \
      test
fi
STATUS=$?

# The result bundle is the only authoritative count. Every log-derived number is
# a heuristic over text that changes shape with the runner, the formatter, and
# the number of bundles in the run — a scheme with two test targets prints one
# summary line per target, and there is no reliable way to tell those apart from
# a per-suite line by grepping.
TOTAL=""
if command -v xcrun >/dev/null 2>&1 && [ -d "$RESULT" ]; then
  TOTAL="$(xcrun xcresulttool get test-results summary --path "$RESULT" --format json 2>/dev/null \
    | awk -F'[:,]' '/"totalTestCount"/{gsub(/[^0-9]/,"",$2); print $2; exit}')"
fi

# Fallback for a run that produced no bundle. Counts come from the RAW log, never
# the formatter: xcpretty silently drops all Swift Testing output. Summed, not
# maxed — with two test bundles the max silently reports the larger one and
# throws the other away, which reads as a smaller suite rather than a bug.
if [ -z "$TOTAL" ]; then
  sum_of() {
    grep -oE "$1" "$LOG" 2>/dev/null | grep -oE '[0-9]+' \
      | awk '{n+=$1} END{print n+0}'
  }
  XCTEST_N="$(sum_of 'Test Suite .All tests. passed|Executed [0-9]+ test')"
  SWITEST_N="$(sum_of 'Test run with [0-9]+ test')"
  TOTAL=$(( ${XCTEST_N:-0} + ${SWITEST_N:-0} ))
fi

ELAPSED="$(kit_elapsed "$(( $(kit_now) - START ))")"

if [ "$STATUS" -ne 0 ]; then
  # Both the log and the result bundle are overwritten on the next run, so an
  # intermittent failure is otherwise unattributable. Preserve it now.
  KEEP="$LOG_DIR/failures/$SAFE-$(date +%Y%m%d-%H%M%S)"
  mkdir -p "$KEEP"
  cp "$LOG" "$KEEP/" 2>/dev/null
  cp -R "$RESULT" "$KEEP/" 2>/dev/null
  printf '\nTESTS FAILED (%s, %s tests) — preserved in %s\n' "$ELAPSED" "$TOTAL" "$KEEP" >&2
  if command -v xcrun >/dev/null 2>&1 && [ -d "$RESULT" ]; then
    xcrun xcresulttool get test-results summary --path "$RESULT" --format json 2>/dev/null \
      | grep -oE '"(title|failureText)"[^,]*' | head -20 >&2
  fi
  exit "$STATUS"
fi

# xcodebuild exits 0 when a filter matches nothing. A green run that executed no
# tests is a false pass, and the most expensive kind.
if [ "$TOTAL" -eq 0 ]; then
  printf '\nFAILED: exit 0 but 0 tests ran — check the scheme or --only-testing filter.\n' >&2
  printf 'Log: %s\n' "$LOG" >&2
  exit 1
fi

printf '\n%s tests passed in %s\n' "$TOTAL" "$ELAPSED"
printf 'Log: %s\n' "$LOG"
